version: '3'
services:
  openresty:
    image: openresty/openresty:1.19.3.1-bionic
    container_name: openresty
    network_mode: host
    restart: always
    logging:
      driver: journald
    volumes:
      - /data/nginx/conf:/usr/local/openresty/nginx/conf
      - /data/nginx/cert:/usr/local/openresty/nginx/cert
      - /data/nginx/dist:/root/dist
      - /data/logs/nginx/:/var/log/nginx/
      - "/etc/localtime:/etc/localtime:ro"

  wechat-gateway:
    build:
      context: .
    hostname: wechat-gateway
    container_name: wechat-gateway
    network_mode: host
    restart: always
    logging:
      driver: journald
    volumes:
      - /data/wechat-gateway:/root/wechat-gateway
      - /data/logs/wechat-gateway:/root/logs/wechat-gateway
      - "/etc/localtime:/etc/localtime:ro"

